#!/usr/bin/env python3
"""Validate an assembled review-commits rules brief."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

GENERATED_MARKER = "Generated by scripts/assemble_rules.py"
PATCH_BASE_MARKERS = (
    "<!-- BEGIN refs/core.md -->",
    "<!-- BEGIN refs/coding-style.md -->",
    "<!-- BEGIN refs/code-logic.md -->",
    "<!-- BEGIN refs/commit-message.md -->",
    "<!-- BEGIN refs/gate-rules.md -->",
    "<!-- BEGIN refs/special-cases.md -->",
    "## Your procedure — 7 mandatory steps",
    "## CSS Class Mapping",
    "Step 3b",
    "Step 3c",
    "Step 3e",
    "THREE-GATE RULE",
    "## Special Cases",
)
MODE_C_BASE_MARKERS = (
    "<!-- BEGIN mode-c-overrides -->",
    "<!-- BEGIN refs/core.md -->",
    "<!-- BEGIN refs/coding-style.md -->",
    "<!-- BEGIN refs/code-logic.md -->",
    "<!-- BEGIN refs/gate-rules.md -->",
    "<!-- BEGIN refs/special-cases.md -->",
    "Mode C — Single-File Review Overrides",
    "## CSS Class Mapping",
    "Step 3b",
    "Step 3c",
    "THREE-GATE RULE",
    "## Special Cases",
)
DT_MARKERS = (
    "<!-- BEGIN refs/dt-binding.md -->",
    "Step 3d",
)
DT_DRIVER_MARKERS = (
    "<!-- BEGIN refs/dt-driver.md -->",
    "Step 3d.3",
)
HARDWARE_MARKERS = (
    "<!-- BEGIN refs/hardware-eng.md -->",
    "Step 3f",
)
MEMORY_SECTION_RE = re.compile(r"<!-- BEGIN refs/memory/(?:(?:active|draft|deprecated|active\+draft|active\+deprecated|draft\+deprecated|active\+draft\+deprecated)/)?([a-z-]+\.md) -->")
BAD_MEMORY_STATUS_RE = re.compile(r"(?m)^Status:\s*(draft|deprecated)\s*$", re.IGNORECASE)
MEMORY_SCOPE_JSON_RE = re.compile(r"<!-- Memory scope files JSON: (.+?) -->")
MEMORY_FILES = {
    "patch-scope": "patch-scope.md",
    "commit-message": "commit-message.md",
    "dt-bindings": "dt-bindings.md",
    "subsystem-specific": "subsystem-specific.md",
}
MODE_C_FORBIDDEN_MEMORY = {"patch-scope", "commit-message"}


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Validate an assembled review-commits rules brief.")
    parser.add_argument("rules_file", help="Path to generated rules brief")
    parser.add_argument("--mode-c", action="store_true", help="Validate Mode C single-file rules")
    parser.add_argument("--dt", action="store_true", help="Require DT/DT-binding schema + DTS rules")
    parser.add_argument("--dt-driver", action="store_true", help="Require driver of_* API rules")
    parser.add_argument("--hardware", action="store_true", help="Require hardware-engineering rules")
    parser.add_argument(
        "--memory",
        action="append",
        default=[],
        metavar="CATEGORY[,CATEGORY...]",
        help="Require selected memory category sections",
    )
    parser.add_argument(
        "--scope-file",
        action="append",
        default=[],
        metavar="PATH",
        help="Expected scope files recorded in the generated rules brief",
    )
    return parser.parse_args(argv)


def split_csv(values: list[str]) -> list[str]:
    items: list[str] = []
    for value in values:
        for item in value.split(","):
            item = item.strip()
            if item:
                items.append(item)
    return items


def normalize_paths(values: list[str]) -> list[str]:
    paths: list[str] = []
    for value in values:
        value = value.strip()
        if value:
            paths.append(value)
    return paths


def require_markers(text: str, markers: tuple[str, ...], errors: list[str]) -> None:
    for marker in markers:
        if marker not in text:
            errors.append(f"missing marker: {marker}")


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    path = Path(args.rules_file)
    if not path.is_file():
        print(f"rules file missing: {path}", file=sys.stderr)
        return 1

    text = path.read_text(encoding="utf-8")
    errors: list[str] = []

    if GENERATED_MARKER not in text:
        errors.append("rules brief is not marked as generated by scripts/assemble_rules.py")

    require_markers(text, MODE_C_BASE_MARKERS if args.mode_c else PATCH_BASE_MARKERS, errors)

    if args.mode_c and "<!-- BEGIN refs/commit-message.md -->" in text:
        errors.append("Mode C rules brief must not include refs/commit-message.md")

    if args.dt:
        require_markers(text, DT_MARKERS, errors)
    elif "<!-- BEGIN refs/dt-binding.md -->" in text:
        errors.append("unexpected DT rules section without --dt")

    if args.dt_driver:
        require_markers(text, DT_DRIVER_MARKERS, errors)
    elif "<!-- BEGIN refs/dt-driver.md -->" in text:
        errors.append("unexpected DT-driver rules section without --dt-driver")

    if args.hardware:
        require_markers(text, HARDWARE_MARKERS, errors)
    elif "<!-- BEGIN refs/hardware-eng.md -->" in text:
        errors.append("unexpected hardware rules section without --hardware")

    memory_categories = split_csv(args.memory)
    scope_files = normalize_paths(args.scope_file)
    unknown_memory = sorted(set(memory_categories) - set(MEMORY_FILES))
    if unknown_memory:
        errors.append("unknown memory categories: " + ", ".join(unknown_memory))
    requested_memory = {MEMORY_FILES[category] for category in memory_categories if category in MEMORY_FILES}
    if args.mode_c:
        forbidden = sorted(MODE_C_FORBIDDEN_MEMORY & set(memory_categories))
        if forbidden:
            errors.append("Mode C requested patch-only memory categories: " + ", ".join(forbidden))
    present_memory = set(MEMORY_SECTION_RE.findall(text))
    missing_memory = sorted(requested_memory - present_memory)
    if missing_memory:
        errors.append("missing memory sections: " + ", ".join(missing_memory))
    if memory_categories and scope_files:
        scope_match = MEMORY_SCOPE_JSON_RE.search(text)
        if not scope_match:
            errors.append("missing memory scope marker")
        else:
            try:
                present_scope_files = json.loads(scope_match.group(1))
            except json.JSONDecodeError as exc:
                errors.append(f"invalid memory scope JSON: {exc}")
            else:
                if not isinstance(present_scope_files, list) or not all(
                    isinstance(item, str) for item in present_scope_files
                ):
                    errors.append("memory scope marker must be a JSON list of strings")
                else:
                    missing_scope_files = sorted(set(scope_files) - set(present_scope_files))
                    if missing_scope_files:
                        errors.append("missing memory scope files: " + ", ".join(missing_scope_files))

    bad_statuses = sorted(set(match.group(1).lower() for match in BAD_MEMORY_STATUS_RE.finditer(text)))
    if bad_statuses:
        errors.append("non-active memory statuses included: " + ", ".join(bad_statuses))

    if errors:
        for error in errors:
            print(error, file=sys.stderr)
        return 1

    print(f"rules brief valid: {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
