repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.7
    hooks:
      - id: ruff-check
        args: [--fix]
        verbose: true
      - id: ruff-format
        verbose: true

  - repo: local
    hooks:
      - id: check-signoff
        name: Check commit signoff
        entry: |
          bash -c 'grep -q "Signed-off-by:" "$1" || { echo ""; echo "WARNING: Missing Signed-off-by line"; echo "Use: git commit -s"; echo ""; exit 1; }'
        args: [--]
        language: system
        stages: [commit-msg]
        verbose: true